In [1]:
import numpy as np
x=np.array([1,2,1,1,1,2,2,1,1])
y=np.array([100,200,100,50,10,20,20,10,10])
len(x),len(y),x.mean(),y.mean()

(9, 9, 1.3333333333333333, 57.77777777777778)

In [2]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(np.reshape(x,(-1,1)),y)
model.coef_,model.intercept_

(array([33.33333333]), 13.333333333333336)

In [4]:
w,b=model.coef_,model.intercept_

In [5]:
newX=3
newX=np.reshape(newX,(-1,1))
newY=newX*w+b
newY, model.predict(newX)

(array([[113.33333333]]), array([113.33333333]))

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LogisticRegression
import numpy as np

In [7]:
train_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='train')
test_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='test')

labels = ['사망', '생존']

In [8]:
x_train = train_df.drop(['name', 'ticket', 'survival'], axis=1)
x_test = test_df.drop(['name', 'ticket', 'survival'], axis=1)
y_train = train_df['survival']
y_test = test_df['survival']

print(x_train.head())

   pclass     sex  age  sibsp  parch   fare embarked
0       2  Female   17      0      0  12.00        C
1       3  Female   37      0      0   9.59        S
2       3    Male   18      1      1  20.21        S
3       3    Male   30      0      0   7.90        S
4       3    Male   25      0      0   7.65        S


In [9]:
transformer = make_column_transformer(
    (OneHotEncoder(), ['pclass', 'sex', 'embarked']),
    remainder='passthrough')
transformer.fit(x_train)
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)

In [10]:
x_train

array([[ 0.  ,  1.  ,  0.  , ...,  0.  ,  0.  , 12.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  9.59],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  1.  , 20.21],
       ...,
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  8.66],
       [ 1.  ,  0.  ,  0.  , ...,  1.  ,  1.  , 52.55],
       [ 0.  ,  1.  ,  0.  , ...,  1.  ,  0.  , 26.  ]])

In [11]:
model = LogisticRegression()

In [12]:
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
print(model.score(x_train, y_train))

0.7945205479452054


In [14]:
print(model.score(x_test, y_test))

0.7763578274760383


In [15]:
model.predict(x_test) [:5]

array([1, 0, 0, 0, 1])

In [16]:
model.predict_proba(x_test)[:5]

array([[0.13246736, 0.86753264],
       [0.90265405, 0.09734595],
       [0.60918187, 0.39081813],
       [0.82355928, 0.17644072],
       [0.35993094, 0.64006906]])