In [1]:
import torch
import numpy as np

vector = torch.tensor([1,2,3,4])
print(type(vector)),print(vector[0])
vector[0]=100
vector

<class 'torch.Tensor'>
tensor(1)


tensor([100,   2,   3,   4])

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available())
print('현재 사용 중인 디바이스 :', device)

In [2]:
import tensorflow as tf

tensor = tf.constant([1,2,3])

tensor = tf.Variable(tensor)
tensor[0].assign(100)

print(tensor.numpy())

[100   2   3]


In [6]:
tensor = tf.constant([1,2,499], dtype=tf.uint8)

tensor = tf.Variable(tensor)
tensor[0].assign(100)

print(tensor.numpy())

[100   2 243]
